FROM node:18-alpine

# Prisma needs openssl
RUN apk add --no-cache openssl

WORKDIR /app

# Copy package files
COPY package*.json ./
COPY prisma ./prisma/

# Install all deps (include devDependencies)
RUN npm install

# Copy source
COPY . .

# Generate prisma client
RUN npx prisma generate

EXPOSE 3000

CMD ["npm", "run", "dev"]
